apiVersion: apps/v1
kind: Deployment
metadata:
  name: uscis-spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-container
        image: 537792915666.dkr.ecr.us-east-1.amazonaws.com/spring-uscis:springuscis-latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-registry-secret
