apiVersion: apps/v1
kind: Deployment
metadata:
  name: uscis-spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uscis-spring-boot-app
  template:
    metadata:
      labels:
        app: uscis-spring-boot-app
    spec:
      containers:
      - name: uscis-spring-boot-app
        image: 537792915666.dkr.ecr.us-east-1.amazonaws.com/spring-uscis:latest
        ports:
        - containerPort: 8080
