name: SpringBoot Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Build Spring Boot application
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
## code piece only to use for debugging
      # - name: Print Directories and Files
      #   run: |
      #     echo "Directories:"
      #     ls -d */

      #     echo "Files:"
      #     ls -p | grep -v /   # Print files excluding directories

            
      - name: Login to Amazon ECR
        run: echo "${{ secrets.ECR_PASS }}" | docker login -u AWS --password-stdin 537792915666.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t 537792915666.dkr.ecr.us-east-1.amazonaws.com/spring-uscis:springuscis-latest --push . 

          
      # - name: Push Docker image to Amazon ECR
      #   run: docker push 537792915666.dkr.ecr.us-east-1.amazonaws.com/spring-uscis:springuscis-latest
